---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: stage (test)
    image: 72636c/stratus:base
    commands:
      - stratus stage
    environment: &test-environment
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      ENVIRONMENT: test
    pull: always
    when:
      event:
        - pull_request

  - name: deploy (test)
    image: 72636c/stratus:base
    commands:
      - stratus deploy
    environment: *test-environment
    pull: always
    when:
      event:
        - pull_request

  - name: sync (test)
    image: amazon/aws-cli
    commands:
      - aws s3 sync --delete www-bucket s3://www.test.bryceandryanforeverandever.net
    environment: *test-environment
    when:
      event:
        - pull_request

  - name: stage (prod)
    image: 72636c/stratus:base
    commands:
      - stratus stage
    environment: *test-environment
    pull: always
    when:
      event:
        - pull_request

  - name: deploy (prod)
    image: 72636c/stratus:base
    commands:
      - stratus deploy
    environment: &prod-environment
      <<: *test-environment
      ENVIRONMENT: prod
    pull: always
    when:
      branch:
        - master
      event:
        - push

  - name: sync (prod)
    image: amazon/aws-cli
    commands:
      - aws s3 sync --delete www-bucket s3://www.bryceandryanforeverandever.net
    environment: *prod-environment
    when:
      branch:
        - master
      event:
        - push

---
kind: signature
hmac: 17d474081a47144966617fb6ace6ba825f207837460d4abf454ae042480a0081
